# Generated by Django 4.1.5 on 2023-01-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatByArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name_sal', models.CharField(max_length=40, verbose_name='Город')),
                ('salary', models.FloatField(verbose_name='Уровень зарплат')),
                ('area_name_vac', models.CharField(max_length=40, verbose_name='Город')),
                ('count', models.FloatField(verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Статистика по городам',
                'verbose_name_plural': 'Статистик по городам',
            },
        ),
        migrations.CreateModel(
            name='StatBySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('published_at', models.CharField(max_length=40, verbose_name='Дата публикации')),
                ('key_skills', models.TextField(verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Статистика по навыкам',
                'verbose_name_plural': 'Статистик по навыкам',
            },
        ),
        migrations.CreateModel(
            name='StatByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(verbose_name='Год')),
                ('salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('salary_vac', models.FloatField(verbose_name='Средняя зарплата - Frontend-программист')),
                ('count', models.FloatField(verbose_name='Количество вакансий')),
                ('count_vac', models.FloatField(verbose_name='Количество вакансий - Frontend-программист')),
            ],
            options={
                'verbose_name': 'Статистика по годам',
                'verbose_name_plural': 'Статистик по годам',
            },
        ),
    ]
