# Generated by Django 4.1.5 on 2023-01-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('salary_vac', models.FloatField(verbose_name='Средняя зарплата - Frontend-программист')),
                ('count', models.FloatField(verbose_name='Количество вакансий')),
                ('count_vac', models.FloatField(verbose_name='Количество вакансий - Frontend-программист')),
            ],
        ),
    ]
