# Generated by Django 4.1.5 on 2023-01-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_project', '0002_statbyyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatByArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_1', models.CharField(max_length=40, verbose_name='Город')),
                ('salary', models.FloatField(verbose_name='Уровень зарплат')),
                ('city_2', models.CharField(max_length=40, verbose_name='Город')),
                ('vacancies', models.FloatField(verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Статистика по городам',
                'verbose_name_plural': 'Статистика по городам',
            },
        ),
        migrations.AlterModelOptions(
            name='statbyyear',
            options={'verbose_name': 'Статистика по годам', 'verbose_name_plural': 'Статистика по годам'},
        ),
    ]
