# Generated by Django 4.1.5 on 2023-01-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_project', '0002_statbyarea_statbyskills_statbyyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statbyskills',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
